export { default as Navbar} from './Navbar'
export { default  as  Home} from './Home'
export { default as SearchFiled} from './pages/SearchFiled'
export { default as Trending} from './pages/Trending'
export { default as VideoTempe} from './pages/VideoTempe'
export { default as Bookmarks} from './Bookmarks'
export { default as Auth} from './Auth'